export const constants = {
	"REQUEST_SHORTENED_LINK_PENDING": "REQUEST_SHORTENED_LINK_PENDING",
	"REQUEST_SHORTENED_LINK_CANCELLED": "REQUEST_SHORTENED_LINK_CANCELLED",
	"DISPLAY_ERROR": "DISPLAY_ERROR", //AddMEssage()
	"CLEAR_ERROR": "CLEAR_ERROR", //ClearMessage()
	"SHORTENED_LINK_SHOW": "SHORTENED_LINK_SHOW", //InputBox.link
	"INPUT_SUBMIT": "INPUT_SUBMIT", //InputBox.submitted
	"INPUT_DIRTY": "INPUT_DIRTY",
	"INPUT_VALID": "INPUT_VALID",
	"INPUT_CHANGE": "INPUT_CHANGE"
}